// src/components/editorFonts.ts
// Modularized font options for the rich text editor

export const fontOptions = [
  // Web-safe fonts
  { label: 'System Font', value: 'system-ui' },
  { label: 'Arial', value: 'Arial, sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: 'Times New Roman, serif' },
  { label: 'Courier New', value: 'Courier New, monospace' },
  { label: 'Trebuchet MS', value: 'Trebuchet MS, sans-serif' },
  { label: 'Verdana', value: 'Verdana, sans-serif' },
  { label: 'Comic Sans MS', value: 'Comic Sans MS, cursive, sans-serif' },
  { label: 'Lucida Console', value: 'Lucida Console, Monaco, monospace' },
  { label: 'Garamond', value: 'Garamond, serif' },
  { label: 'Palatino', value: 'Palatino Linotype, Book Antiqua, Palatino, serif' },
  { label: 'Impact', value: 'Impact, Charcoal, sans-serif' },
  { label: 'Tahoma', value: 'Tahoma, Geneva, sans-serif' },
  { label: 'Helvetica', value: 'Helvetica, Arial, sans-serif' },
  { label: 'Century Gothic', value: 'Century Gothic, CenturyGothic, AppleGothic, sans-serif' },
  { label: 'Franklin Gothic Medium', value: 'Franklin Gothic Medium, Arial Narrow, Arial, sans-serif' },
  { label: 'Candara', value: 'Candara, Calibri, Segoe, Segoe UI, Optima, Arial, sans-serif' },
  { label: 'Optima', value: 'Optima, Segoe, Segoe UI, Candara, Calibri, Arial, sans-serif' },
  { label: 'Geneva', value: 'Geneva, Verdana, sans-serif' },
  { label: 'Segoe UI', value: 'Segoe UI, Segoe, Tahoma, Geneva, Verdana, sans-serif' },
  { label: 'Calibri', value: 'Calibri, Candara, Segoe, Segoe UI, Optima, Arial, sans-serif' },
  { label: 'Rockwell', value: 'Rockwell, Courier Bold, Courier, Georgia, Times, Times New Roman, serif' },
  { label: 'Consolas', value: 'Consolas, monaco, monospace' },
  { label: 'Futura', value: 'Futura, Trebuchet MS, Arial, sans-serif' },
  { label: 'Brush Script MT', value: 'Brush Script MT, cursive' },
  // Google Fonts (add these to index.html or import via CSS)
  { label: 'Roboto', value: 'Roboto, Arial, sans-serif' },
  { label: 'Lato', value: 'Lato, Arial, sans-serif' },
  { label: 'Montserrat', value: 'Montserrat, Arial, sans-serif' },
  { label: 'Merriweather', value: 'Merriweather, serif' },
  { label: 'Oswald', value: 'Oswald, Arial, sans-serif' },
  { label: 'Open Sans', value: 'Open Sans, Arial, sans-serif' },
  { label: 'Raleway', value: 'Raleway, Arial, sans-serif' },
  { label: 'PT Sans', value: 'PT Sans, Arial, sans-serif' },
  { label: 'Nunito', value: 'Nunito, Arial, sans-serif' },
  { label: 'Playfair Display', value: 'Playfair Display, serif' },
  { label: 'Source Code Pro', value: 'Source Code Pro, monospace' },
  { label: 'Fira Mono', value: 'Fira Mono, monospace' },
  { label: 'Inconsolata', value: 'Inconsolata, monospace' },
];
